name = "ExactPredicates"
uuid = "429591f6-91af-11e9-00e2-59fbe8cec110"
authors = ["Pierre Lairez <pierre@lairez.fr>"]
description = "Fast and exact geometrical predicates in the Euclidean plane"
licence = "MIT"
version = "2.2.6"

[deps]
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"

[compat]
IntervalArithmetic = "^0.21, 0.22"
StaticArraysCore = "^1.4"
julia = "^1.1"
